name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"

  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Install vsce and ovsx
        run: npm install -g vsce ovsx typescript

      - name: Build extension
        run: tsc

      - name: Package extension
        run: vsce package --out extension.vsix

      - name: Publish to Open VSX
        if: startsWith(github.ref, 'refs/tags/')
        run: ovsx publish --packagePath extension.vsix -p ${{ secrets.OPENVSX_TOKEN }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release_tag
        uses: softprops/action-gh-release@v2
        with:
          files: extension.vsix
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Latest Release
        if: github.ref == 'refs/heads/master'
        id: create_release_latest
        uses: softprops/action-gh-release@v2
        with:
          files: extension.vsix
          tag_name: latest
          name: Latest Release
          body: |
            Automated release of the latest build.
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
